name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ '*' ]


env:
  working-directory: Sources
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  dotnet-version: 8.0.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.working-directory }}

    - name: Build
      run: dotnet build -c Release --no-restore --verbosity normal
      working-directory: ${{ env.working-directory }}

    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      working-directory: ${{ env.working-directory }}

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    # - name: Run mutation tests
    #   run: |
    #     dotnet tool restore
    #     dotnet stryker --reporter dashboard
    #   working-directory: ${{ env.working-directory }}
    #   env:
    #       STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
